version: "3"


services:
  web:
    container_name: ais_web
    image: ais_monitor
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c " python manage.py collectstatic --no-input && gunicorn --timeout 6000 djangoProject1.wsgi:application --bind 0.0.0.0:3000"

    volumes:
      - static_volume:/djangoProjectdw/staticfiles

    environment:
      - DEBUG='True'

  nginx:

    container_name: ais_nginx
    image: ais_nginx
    build: ./nginx
    volumes:
      - static_volume:/staticfiles
    ports:
      - 8085:80
    depends_on:
      - web
volumes:
  static_volume: